[world]
file = "worlds/world_2.oct"
palette = "worlds/palette.txt"
camera_position = [
    320.0,
    100.0,
    320.0,
]

[rendering]
lod_subdivide_distance = 500.0
lod_merge_distance = 1000.0
chunk_lod_distance = 800.0
fov_degrees = 70.0
near_plane = 0.10000000149011612
far_plane = 5000.0
camera_speed_multiplier = 3.814697265625

[atmosphere]
fog_density = 0.0005000000237487257
time_of_day = 0.5

[effects]
depth_of_field = false
dof_focus_distance = 200.0
dof_blur_size = 2.0
bloom = true
bloom_threshold = 0.800000011920929
bloom_intensity = 0.30000001192092896

[debug]
show_fps = true
show_chunk_stats = true
